# Configuración para la universidad
db.url=jdbc:mysql://172.30.16.76:3306/gym_db
db.user=kssoto29
db.password=67001429

# Para tu PC personal (descomenta cuando estés en casa):
# db.url=jdbc:mysql://localhost:3306/gym_db
# db.user=root
# db.password=tu_password