# Configuracion MySQL (actual)
#mysql.url=jdbc:mysql://172.30.16.52:3306/gym_db
#mysql.user=kssoto29
#mysql.password=67001429

# Configuracion SQLite (placeholder, ajustaremos credenciales/ruta cuando la compartas)
sqlite.url=jdbc:sqlite:C:/Users/sala7.FI-LABSISTEMAS.002/Documents/gym_db.db
sqlite.user=
sqlite.password=

# Compatibilidad con configuracion antigua
db.url=jdbc:mysql://172.30.16.36:3306/gym_db
db.user=kssoto29
db.password=67001429

